name: Update ESPN forecast
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1' # Mondays (1) at 12:00pm

jobs:
  run_script:
    if: github.repository_owner == 'reichlab'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout nba-predictions repo
      uses: actions/checkout@v3
      with:
        path: nba-predictions
    
    - name: Setup GitHub Action for R language
      uses: r-lib/actions/setup-r@v2

    - name: Install R script dependencies
      working-directory: ./nba-predictions
      run: Rscript .github/workflows/install_dependencies.R
      env:
        GITHUB_PAT: ${{secrets.GH_TOKEN}}

